-- local blink = require("blink")
-- local capabilities = vim.lsp.protocol.make_client_capabilities()

-- -- Optionally enhance capabilities if you're using cmp_nvim_lsp
-- local ok, cmp_lsp = pcall(require, "cmp_nvim_lsp")
-- if ok then
--   capabilities = cmp_lsp.default_capabilities(capabilities)
-- end

-- local servers = {
--   lua = {
--     cmd = { "lua-language-server" },
--     settings = {
--       Lua = {
--         diagnostics = { globals = { "vim" } },
--       },
--     },
--   },
--   python = {
--     name = "basedpyright",
--     cmd = { "basedpyright-langserver", "--stdio" },
--   },
--   java = {
--     name = "jdtls",
--     cmd = { "jdtls" },
--     -- optional: customize your root_dir logic for jdtls here
--     root_dir = function()
--       return vim.fn.getcwd() -- replace with smarter project root detection if needed
--     end,
--   },
-- }

-- -- Auto start the correct LSP per filetype
-- for ft, config in pairs({
--   lua = "lua",
--   python = "python",
--   java = "java",
-- }) do
--   vim.api.nvim_create_autocmd("FileType", {
--     pattern = config,
--     callback = function()
--       blink.start(vim.tbl_deep_extend("force", servers[ft], {
--         name = ft,
--         capabilities = capabilities,
--       }))
--     end,
--   })
-- end
